### ISSUE TITLE
[BUG] Voice Navi - weird Spanish accent

### ISSUE THREAD

**Issue by 0xlne** [junjunguo/PocketMaps#140]
Using PocketMaps v3.4.34 on Android 10

I have English/United Kingdom set as regional/language setting.
Voice navigation results in words spoken in English, but with a weird Spanish accent.
Numbers are spoken fully in Spanish though.

**Comment by Starcommander** [comment]
Hello @0xlne !

Thanks for opening this issue.
Where did you get the app from?
Because there is no official Version 3.4.34 of Pocketmaps.

It seems, that I am using any Voice, ignoring the current locale.
Basically the voice should be in english language, as the text is not translated.
Maybe I can use this opportunity to also translate the voice-text.

Affected code:
com/junjunguo/pocketmaps/navigator/NaviVoice.java: Line 129

Best regards,
Paul

**Comment by 0xlne** [comment]
@Starcommander thx for responding!
I got it from f-droid; I noticed the minor version is just a concat, so v3.4 is v3.4.34 on f-droid.
Glad you could pinpoint the root cause so fast!

**Comment by feelingwalnut** [comment]
i had stopped using maps (maps.me fork) because of mp downloading issues, routing issues (telling me to turn off the highway at every exit and then return to highway)
maps.me fixed some of those with added bloat of ads and for purchase guides.

so i'm glad this english/spanish issue is being repaired, as it had brought me here to report the issue and was the only thing preventing me from using this extremely lightweight app.

**Comment by Starcommander** [comment]
@feelingwalnut 
@0xlne 
Maybe anyone can test the pre-release:
https://github.com/junjunguo/PocketMaps/releases/tag/3.5-pre1

- Should select voice correctly, if installed.
- Debug_Simulator activated: just plan a route, and start navigation.
  On first time this will simulate moving along the route.
- Voice selection on main_menu added, for test only.
  Starts a tts app for installing additional voices, if present.

Warning: installing this apk may delete stored data (maps, favourites, trackingrecords)

**Comment by Starcommander** [comment]
Open questions:
- What happens, if native-language-voice and english-voice is missing on device?
  Maybe it is possible to uninstall voices to test this case?
- Is it possible to install further voices?
  Need of an external TTS toolkit (like Flite TTS)?

**Comment by feelingwalnut** [comment]
voice appears to work properly now for the voice that is selected in the general management/ language and input/ text-to-speech settings menu of android 10
the new menu option will open Google TTS voice data menu for downloading voices, voices will download but there is no way from that menu to change the voices.
i don't have an actual device without TTS to test on. but bluestacks without TTS services installed at all works fine in debug, it does not play any voice (obviously) but the mapping works and the routing works.
the new menu option brings up an "open with" prompt which in my case asks for fdroid or aurora store instead of google TTS voice data menu.
aurora store tries to find "pname:com.svox.langpack.installer" and obviously fails to.

at the moment TTS speaks "feets" instead of the proper "feet" i am not sure if this is application related.

**Comment by Starcommander** [comment]
@feelingwalnut 
This is my fault.
- 1 meter, 10 meters
- 1 feet, 10 feet
Is this correctly?
(My native lang is german.)

**Comment by feelingwalnut** [comment]
I thought your native wasnt english although it is very good.

1 meter, 10 meters
1 foot, 10 feet

On March 31, 2020 6:24:55 AM EDT, Starcommander <notifications@github.com> wrote:
>@feelingwalnut 
>This is my fault.
>- 1 meter, 10 meters
>- 1 feet, 10 feet
>Is this correctly?
>(My native lang is german.)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/junjunguo/PocketMaps/issues/140#issuecomment-606536273

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Starcommander** [comment]
I improved the voice-selection now.
TODO regarding Dialog.java:
- TakeSourcesOut regarding voice to separate file
- ShowAllInstalledTtsEngines
- TranslateLang: tview.setText

**Comment by Starcommander** [comment]
There is still the typo "feets" in java code.
Also using DisplayLanguage instead of ISO3 prevents Pocketmaps from using native language.
Fixed now.

**Comment by Starcommander** [comment]
New release 3.7 is available in F-Droid, and soon on Play-Store.
