### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by natrius** [junjunguo/PocketMaps#91]
Set the map as start, not the map-download screen. The map download-screen should be somwhere in the settings. Are there settings? I cannot find any, unfortunately :/

Mybe let choose what the start-display should be. Map, Favorites, Map-download, Navigation

**Comment by Starcommander** [comment]
On the screen for changing map there is a small menu.
Also you have some settings on the Map-View using the gear-button.

I do not have much time the next 2 weeks.
So I will look for issues afterwards.

**Comment by natrius** [comment]
Don't worry, take the time you need. 

I try to describe better, what i mean:
Basically, when the app starts it should show the map, not the map-download screen. Because, yeah, its a map-app and a navigation-app and not a map-downloading app :D

On the map, there is the settings-menu - open instead a bigger menu (side-scrolling?) with the following content, as the main-settings:
- General (change map directory, ...)
- Navigation (fastest, shortest, navi voice, light-sensors and so on)
- Map download (Show downloaded maps, show where updates are available, ...)
- About (Current version, help, submit bugs, visit homepage, rate Pocket Maps [if you worry about it, pop it up every month once, something like that :D ])
- Close

The settings would be more consistent and central available. And when in the map-download for example, the 3 dots on the right top corner would just show the settings menu again. 

And, i like the 3d approach, really smooth implemented!

**Comment by Starcommander** [comment]
I would suggest to keep settings splitted.
Because some options are only meaningful on the _in-map-view_ (nav-options,... ) and some other options are better outside of the _in-map-view_, for example "change map directory" is no good idea inside a loaded map.

To set the map as main screen has some drawbacks, because it is possible to delete all maps, then you dont have a main screen anymore, the same on first start, or changing maps directory.

My suggestion:

1. Instead of "change map" we call that option "close map".
- That should illustrate to go back to main view.
2. On that main view adding a help is a good idea. (via three dots)
- There we could explain "swipe out for delete" and all of your suggested points.
3. And we could expand the _three-dots-menu_ with additional settings like selecting a default map to open on startup.

**Comment by natrius** [comment]
Yeah, you are right with the split approach, i see that now. 

For the Map vs Map-Download at start: 
Would it be possible like, 
if{map == downloaded && map == set as default} show map when opening
or
if{mapstart == first || mapfolder == empty || map == !set as default] show mapdownload

I hope you get what i mean, its just a thought about it.

**Comment by Starcommander** [comment]
Should be available in next release.
