### ISSUE TITLE
Long-press on the map

### ISSUE THREAD

**Issue by natrius** [junjunguo/PocketMaps#92]
For faster access to navigation, long pressing on the map opens a menu with:

- "Add as Favorite": Opens the favorites menu with adding information and so on
- "Navigate to": opening the navigation-panel, "navigate to" with the pressed location and "navigate from" already pre-filled with "Current location"

**Comment by Starcommander** [comment]
I have changed the behaviour of navigation input fields.
So now some quick buttons are directly on that navigation menu, with from/to fields.
Entering lat and lon manually is now hidden in the deeper menu, because not often used.
Not the solution as you suggested, but should be an other way to improve user interface.

**Comment by natrius** [comment]
Correct, but still good approach. But the only way to enter Favorites is via navigation menu and the star-button?

**Comment by Starcommander** [comment]
This commit should also improve the way howto add favourites.
