### ISSUE TITLE
Error after downloading the map

### ISSUE THREAD

**Issue by jerryn70** [junjunguo/PocketMaps#99]
I think I wasted my 1gb for downloading. After downloading the map inside the app shows 400+mb . And when I click the map it shows error . See screenshot. 
![](https://i.imgur.com/iNyRuka.png)

**Comment by Starcommander** [comment]
Hi jerryn70.

Thanks for your report.
I also tried to download, and it seems there was a problem with the server, that I restarted now.
Also I will change the visibility behaviour in the notification-bar, because the download is sometimes not showing.

Maybe you can retry to download, and post the results?
Best regards.

**Comment by Starcommander** [comment]
Which country/state are you missing?
Or what do you think is incomplete?
India is included in OSM.

**Comment by jerryn70** [comment]
Not all roads are marked in the map.
